
C_interview_questions.out: C_interview_questions.o
	gcc -g C_interview_questions.o -o C_interview_questions.out

C_interview_questions.o: C_interview_questions.c
	gcc -g -ansi -pedantic -Wall *.c -c


clean:
	rm C_interview_questions.out C_interview_questions.o