%%  DESCRIPTION: Generate output .txt file with final results
%%  INPUT: 'fidWrite' is the file ID of output file, 'resultsTable' is the table
%%            generated by calling PostProcessResults()
%%  OUTPUT: NA
%%  ERRORS: NA
%%  LAST MODIFIED: 24/07/2018

function WriteResultsToFile (fidWrite, resultsTable)
  numOfRows = rows(resultsTable);
  for curRow = 1:numOfRows
    fprintf(fidWrite, "%s)", num2str(curRow));
    fprintf(fidWrite, "%s\n", char(resultsTable(curRow, 1)));
    for curCol = 2:3
      fprintf(fidWrite, "%s\t", deblank(char(resultsTable(curRow, curCol))));
    endfor
    for curCol = 4:5
      fprintf(fidWrite, "%d\t", cell2mat(resultsTable(curRow, curCol)));
  endfor
    fprintf(fidWrite, "\n\n");
  endfor
endfunction
