%%  DESCRIPTION: Get AVS data based on search criteria (input parameters)
%%  INPUT: 'resultsTable' is generated by calling AnalyzeAVSLog(). 'trigNum' is
%%          the trigger num to search, 'distNum' is the distance num to search,
%%          'noiseNum' is the noise number to search. Any/All of the search
%%          parameters can be '-1', which means that it is not relevant for the
%%          search. e.g. to search for all trigger number 4 do:
%%          GetAVSData(resultsTable, 4, -1, -1)
%%  OUTPUT: 'dataTable' is a table that contains all of the search results.
%%            if no results are found, 0 is returned.
%%  ERRORS: NA
%%  LAST MODIFIED: 25/07/2018

function dataTable = GetAVSData(resultsTable, trigNum, distNum, noiseNum)
  numOfRows = rows(resultsTable);
  curDataRow = 1;
  for curRow = 1:numOfRows
    isCurDataRelevant = 0;
    curStr = char(resultsTable(curRow, 6));
    if (strcmp(curStr, "-1"))
      continue;
    endif
    curIDs = strsplit(curStr,".");
    if (-1 != trigNum)
      if (str2num(char(curIDs(1,1))) == trigNum)
        isCurDataRelevant = 1;
      else
        continue;
      endif
    endif
    if (-1 != distNum)
      if (str2num(char(curIDs(1,2))) == distNum)
        isCurDataRelevant = 1;
      else
        continue;
      endif
    endif
    if (-1 != noiseNum)
      if (str2num(char(curIDs(1,3))) == noiseNum)
        isCurDataRelevant = 1;
      else
        continue;
      endif
    endif
    if (isCurDataRelevant)
      dataTable(curDataRow, 1:6) = resultsTable(curRow, 1:6);
      ++curDataRow;
    endif
  endfor
  if (!exist('dataTable', 'var'))
    dataTable = 0;
  endif
endfunction
