%%  DESCRIPTION: Do postprocessing on table to put trigger and command that were 
%%                recorded seperately by alexa, into the same row
%%  INPUT: 'oldResultTable' is the processed result table generated by calling 
%%            CreateResults()
%%  OUTPUT: 'resultTable' is the post-processed table
%%  ERRORS: NA
%%  LAST MODIFIED: 24/07/2018

function resultTable = PostProcessResults (oldResultTable)
  numOfRows = rows(oldResultTable);
%  newCurRow = 1;
  curNewRow = 1;
  for curRow = 2:numOfRows
    curStr = char(oldResultTable(curRow,1));
    if (isempty(strfind(curStr, "alexa")))
      prevStr = char(oldResultTable(curRow-1,1));
      curStr = char(oldResultTable(curRow,1));
      newStr = strcat(prevStr, curStr);
      oldResultTable(curRow-1, 1) = cellstr(newStr);
      oldResultTable(curRow-1, 2:5) = oldResultTable(curRow, 2:5);
      oldResultTable(curRow, 1:5) = " ";
    endif
  endfor
  for curRow = 1:numOfRows
%    curStr = char(oldResultTable(curRow,1));
    if (strcmp(char(oldResultTable(curRow,1))," "))
      continue;
    else
      resultTable(curNewRow,1:5) = oldResultTable(curRow, 1:5);
      ++curNewRow;
    endif
  endfor
endfunction